var config = {
  lineHeight: {
    propKey: "lineHeight",
    valueMap: {
      none: "1px",
      shorter: "1.25px",
      short: "1.375px",
      base: "1.5px",
      tall: "1.625px",
      taller: "2px",
      "3": "12px",
      "4": "2xs",
      "5": "sm",
      "6": "lg",
      "7": "xl",
      "8": "2xl",
      "9": "36px",
      "10": "3xl",
    },
    change: {
      type: "typeChange (from absolute to px)",
      action: "Change to px",
    },
  },
  letterSpacing: {
    propKey: "letterSpacing",
    valueMap: {
      xxs: "2xs",
    },
  },
  radius: {
    propKey: "radius",
    valueMap: {
      sm: "xs",
      md: "sm",
      lg: "md",
      xl: "lg",
      pill: "25",
    },
  },
  fontSize: {
    propKey: "fontSize",
    valueMap: {
      xxs: "2xs",
    },
  },
  size: {},
  spacing: {},
  space: {},

  // spacing
  m: {},
  margin: {},
  mt: {},
  marginTop: {},
  mr: {},
  marginRight: {},
  mb: {},
  marginBottom: {},
  ml: {},
  marginLeft: {},
  mx: {},
  my: {},
  p: {},
  padding: {},
  pt: {},
  paddingTop: {},
  pr: {},
  paddingRight: {},
  pb: {},
  paddingBottom: {},
  pl: {},
  paddingLeft: {},
  px: {},
  py: {},
  color: {},
  bg: {},
  background: {},
  bgColor: {},
  opacity: {},

  //font
  fontFamily: {},
  fontWeight: {},
  textAlign: {},
  fontStyle: {},
  textTransform: {},
  textDecoration: {},

  // size
  w: {},
  width: {},
  h: {},
  height: {},
  minW: {},
  minWidth: {},
  maxW: {},
  maxWidth: {},
  minH: {},
  minHeight: {},
  maxH: {},
  maxHeight: {},
  d: {},
  display: {},
  boxSize: {},
  verticalAlign: {},
  overflow: {},
  overflowX: {},
  overflowY: {},

  //border
  border: {},
  borderWidth: {},
  borderStyle: {},
  borderColor: {},
  borderTop: {},
  borderTopWidth: {},
  borderTopStyle: {},
  borderTopColor: {},
  borderRight: {},
  borderRightWidth: {},
  borderRightStyle: {},
  borderRightColor: {},
  borderBottom: {},
  borderBottomWidth: {},
  borderBottomStyle: {},
  borderBottomColor: {},
  borderLeft: {},
  borderLeftWidth: {},
  borderLeftStyle: {},
  borderLeftColor: {},

  borderRadius: {},
  borderTopLeftRadius: {},
  borderTopRightRadius: {},
  borderBottomRightRadius: {},
  borderBottomLeftRadius: {},
  borderTopRadius: {},
  borderRightRadius: {},
  borderBottomRadius: {},
  borderLeftRadius: {},

  pos: {},
  position: {},
  zIndex: {},
  top: {},
  right: {},
  bottom: {},
  left: {},
  shadow: {},
};

module.exports = {
  config,
};
